server_port: 18080

model_openapi:
  endpoint: https://genai-openapi.sec.samsung.net/dxhq/trial/api-llm
  client_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6IjkzYWMzMjY1LTljNzktNDE1ZS1hNDUwLTYwNzY3ZTY2Yjk2Ny0xMDMyOCIsImNsaWVudFNlY3JldCI6ImlrV0VFS3ZmWHFNYUxUQjZMenY5ZVlBRU5BdVcycXdSIiwiZXhwIjoxNzk1MTAwMzk5fQ.QV9hl4pJvbiPdOXSYMV1GfZtzv0fw7K8jGl39vABIGU
  pass_key: Bearer eyJ4NXQiOiJNV0l5TkRJNVlqRTJaV1kxT0RNd01XSTNOR1ptTVRZeU5UTTJOVFZoWlRnMU5UTTNaVE5oTldKbVpERTFPVEE0TldFMVlUaGxNak5sTldFellqSXlZUSIsImtpZCI6Ik1XSXlOREk1WWpFMlpXWTFPRE13TVdJM05HWm1NVFl5TlRNMk5UVmhaVGcxTlRNM1pUTmhOV0ptWkRFMU9UQTROV0UxWVRobE1qTmxOV0V6WWpJeVlRX1JTMjU2IiwidHlwIjoiYXQrand0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJmMTJkMWRiYS1lOWM0LTQ3MzktOGRmNy03Y2IxZjM1MTIxZGEiLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6ImtYMTJUWHV2TkhzZDF0OVpsMEtyd19uNzZCQWEiLCJuYmYiOjE3ODcyMTc2NjUsImF6cCI6ImtYMTJUWHV2TkhzZDF0OVpsMEtyd19uNzZCQWEiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvaW5ub3ZhdGlvbi13c28yLnNlYy5zYW1zdW5nLm5ldDo0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjQ5NDI5Nzc2NjUsImlhdCI6MTc4NzIxNzY2NSwianRpIjoiMjQ5MDkwY2QtMTY0Yy00MjgzLWFiMjktMWJlMmYyNWFkNTdkIiwiY2xpZW50X2lkIjoia1gxMlRYdXZOSHNkMXQ5WmwwS3J3X243NkJBYSJ9.cVZnFN78sGI4hPIYe44xLppq-40nzCEr0k5wGsJgpX2I0vEh0weFgZ9C9IJwneqLVmJ-tGk-ayVHXPEilSvnidBA1uOmxT_ZGH81GGem3fXwA5lyMeqXTSU2rdSuKNPDVuEYypTreTd9Wih5_8GgtLFlpp118uZE53gVEgQ9SlgmVxV0yzzqSQA4AwbmKBF_pVRFw18jyAR4CLok1M3oN3To0cx3cUCLfwSb8yWVill1QVMCGiVUlKkatPUfDjOamOB6xdpkRh28tRAS7mK8JF8w875V6azYrnInAazjLOodgudzCLMS87-tLPav_TilrYvoIs3NeH7S0Jsq3z3uTQ
  root_model_id: 605
  system_model_id: 81

mongodb_mcp:
  host: 10.240.35.180
  port: 10420

milvus_mcp:
  host: 10.240.35.180
  port: 10422

postgresql_db:
  host: 10.240.35.180
  port: 5432
  name: cosmoData
  user: postgres

object_storage:
  bucket: cosmo-storage-stage
  endpoint: https://gage.ap-northeast-2.samsungspc.com
  access_key: AKIA5PMO9S8UVFAFT68P
  secret_key: gCBynEY51EVVuV901dEybGl8JnwoPkQy9YK7AbjW
  